/**
 * Users domain — storage methods related to users, authentication, OTP,
 * real-time chat, AI chat, family members, medical data, push subscriptions,
 * notification preferences, referrals, waitlist, patient documents, and bug reports.
 *
 * Implementation: DatabaseStorage in ./database-storage.ts
 * Interface slice exported for documentation and tooling.
 */
import type { IStorage } from "./interface";

export type UsersDomain = Pick<
  IStorage,
  | "getUser"
  | "getUserByEmail"
  | "getAllUsers"
  | "getUsersByIds"
  | "getUserListPaginated"
  | "createUser"
  | "updateUser"
  | "deleteUser"
  | "purgeUnverifiedUser"
  | "getRealtimeConversations"
  | "getRealtimeMessages"
  | "createRealtimeMessage"
  | "getOrCreateRealtimeConversation"
  | "getConversationForAppointment"
  | "lockConversation"
  | "getConversation"
  | "getAllConversations"
  | "createConversation"
  | "deleteConversation"
  | "getMessagesByConversation"
  | "createMessage"
  | "updateUserOtp"
  | "verifyUserEmail"
  | "getNotificationPreferences"
  | "upsertNotificationPreferences"
  | "addPushSubscription"
  | "removePushSubscription"
  | "getPushSubscriptions"
  | "getOrCreateReferralCode"
  | "getUserByReferralCode"
  | "createReferral"
  | "getReferralByReferredUser"
  | "getReferralsByReferrer"
  | "qualifyReferral"
  | "getReferralLeaderboard"
  | "createWaitlistEntry"
  | "getWaitlistEntry"
  | "getWaitlistEntriesByPatient"
  | "getActiveWaitlistEntries"
  | "updateWaitlistEntry"
  | "cancelPatientActiveWaitlistEntries"
  | "createPatientDocument"
  | "getPatientDocument"
  | "getPatientDocuments"
  | "updatePatientDocument"
  | "deletePatientDocument"
  | "getPatientDocumentsSharedWithProvider"
  | "getAllPatientDocuments"
  | "createBugReport"
  | "getBugReport"
  | "getBugReportsByUser"
  | "getAdminBugReports"
  | "updateBugReport"
  | "createBugReportComment"
  | "getBugReportComments"
  | "getFamilyMembersByUser"
  | "getFamilyMember"
  | "createFamilyMember"
  | "updateFamilyMember"
  | "deleteFamilyMember"
  | "getFamilyMemberAppointments"
  | "getFamilyMemberDocuments"
  | "getFamilyMemberConsents"
  | "addFamilyMemberConsent"
  | "getMedicationsByUser"
  | "getMedication"
  | "createMedication"
  | "updateMedication"
  | "deleteMedication"
  | "getMedicationLogs"
  | "logMedicationDose"
  | "deleteMedicationLog"
  | "getPrescription"
  | "getPrescriptionsByPatient"
  | "createPrescription"
  | "getMedicalHistoryByPatient"
  | "createMedicalHistory"
  | "getHealthMetricsByPatient"
  | "createHealthMetric"
  | "deleteHealthMetric"
  | "createPatientConsent"
  | "getPatientConsents"
  | "getRefreshToken"
  | "getRefreshTokenByHash"
  | "createRefreshToken"
  | "deleteRefreshToken"
  | "deleteRefreshTokenByHash"
  | "deleteRefreshTokensByUser"
  | "getUserNotifications"
  | "createUserNotification"
  | "markNotificationRead"
  | "getUnreadNotificationCount"
  | "markAllNotificationsRead"
  | "getUnreadChatCounts"
  | "toggleConversationFlag"
  | "checkIdempotencyKey"
  | "setIdempotencyKey"
>;
